---
ace:
  - stance: permit
    protocol: tcp
    srcaddr: 10.10.10.0 0.0.0.255
    srcport:  
    dstaddr: 192.168.1.0 0.0.0.31
    dstport: 80
    log: log

  - stance: deny
    protocol: udp
    srcaddr: 172.17.5.0 0.0.0.255
    srcport: 50
    dstaddr: 192.168.7.1 0.0.0.3
    dstport: 
    log:
